import 'base_evaluate_comments_tool.dart';

/// evaluate_comment_llm_generation_tool.dart
/// Tool to evaluate whether comments in the changed code were LLM generated.

class EvaluateCommentLlmGenerationTool extends BaseEvaluateCommentsTool {
  EvaluateCommentLlmGenerationTool(super.tracker);

  @override
  String get name => 'evaluate_comment_llm_generation';

  @override
  String get description =>
      'Evaluates whether the comments added or modified in the recent commits were likely generated by an LLM (e.g., hallucinations, LLM thinking tags, over-verbose AI speak).';

  @override
  String getPromptInstructions() {
    return '''
1. Determine if any of the provided comments exhibit signs of being LLM generated.
2. Look for obvious LLM artifacts such as:
   - `<thought>` or `</thought>` tags.
   - Phrases like "Here is the code you requested", "As an AI language model", "I have implemented".
   - Unnaturally verbose or robotic explanations that over-explain trivial syntax.
   - Comments that hallucinate non-existent features or APIs.
3. For each comment that appears LLM generated, cite the File, the Commit, and explain why it appears to be generated by an AI without human review.
4. If no comments appear LLM generated, state that the comments appear to be human-written or appropriately curated.
''';
  }
}
