import 'base_evaluate_comments_tool.dart';

/// evaluate_comment_llm_generation_tool.dart
/// Evaluates whether comments in changed code were
/// LLM generated. Returns structured JSON.

class EvaluateCommentLlmGenerationTool extends BaseEvaluateCommentsTool {
  EvaluateCommentLlmGenerationTool(super.tracker);

  @override
  String get name => 'evaluate_comment_llm_generation';

  @override
  String get description => 'Evaluates whether the comments added or modified '
      'in recent commits were likely generated by an LLM '
      '(e.g., hallucinations, LLM thinking tags, '
      'over-verbose AI speak). Returns structured JSON.';

  @override
  List<String> getEvaluationCriteria() {
    return [
      'Look for obvious LLM artifacts: <thought> or '
          '</thought> tags, phrases like "Here is the '
          'code you requested" or "As an AI language '
          'model".',
      'Detect unnaturally verbose or robotic '
          'explanations that over-explain trivial syntax.',
      'Identify comments that hallucinate non-existent '
          'features or APIs.',
      'For each comment that appears LLM generated, '
          'cite the File and Commit, and explain why it '
          'appears to be AI-generated without human '
          'review.',
    ];
  }
}
