import '../mcp_prompt.dart';

/// rw_git_mcp_code_review_reporting_prompt.dart
/// Provides the rw-git-mcp-code-review-reporting skill as an MCP Prompt.
///
/// GENERATED FILE — do not edit by hand. Edit the canonical skill at
/// `.agents/skills/rw-git-mcp-code-review-reporting/SKILL.md` and run
/// `dart run tool/sync_prompts.dart`.
class RwGitMcpCodeReviewReportingPrompt implements McpPrompt {
  @override
  String get name => 'rw-git-mcp-code-review-reporting';

  @override
  String get description =>
      'Specialized workflow for generating a Code Review & Merge Risk Report, focusing on PR diffs, merge conflicts, and AI comment evaluation.';

  @override
  List<Map<String, dynamic>> get messages => [
        {
          'role': 'user',
          'content': {
            'type': 'text',
            'text': _promptText,
          }
        }
      ];

  static const String _promptText = r'''
<role>
You are a Staff Engineer specializing in Code Review and Integration Risk. Your objective is to use the `rw_git` server's tools to assess the quality of incoming code changes, predict merge conflicts, and evaluate documentation/comments.
</role>

<constraints>
1. **Data Offloading (CRITICAL)**: ALL verbose analytical tools will offload their JSON responses to the local filesystem (e.g., `.rw_git/reports/...`) to prevent your context window from overflowing. You MUST actively read these offloaded JSON files (using file reading tools) iteratively, synthesize their insights, and extract business value. Do not regurgitate file paths.
</constraints>

<workflow>
Follow these steps to conduct a Code Review and Integration Risk deep-dive.

<step id="1" name="Scope Preparation & Context">
- Determine if the repository is local or remote, and if you need to fetch/clone it. 
- Use `is_git_repository` to ensure you are in a valid Git directory.
- Use `checkout_branch` to switch to the branch being reviewed.
</step>

<step id="2" name="PR Diff & Integration Risk">
- **Diff Risk**: Run `analyze_pr_diff` to extract risk signals from the changes.
- **Merge Conflicts**: Run `predict_merge_conflicts` against the target integration branch to proactively identify integration pain points.
- **Code Quality**: Run `analyze_code_quality_with_authors` on the diff's context if author attribution is needed.
</step>

<step id="3" name="Comment & Documentation Evaluation">
- **LLM Detection**: Run `evaluate_comment_llm_generation` to detect if the newly added comments appear to be generated by a low-quality LLM prompt.
- **Necessity**: Run `evaluate_comment_necessity` to flag redundant comments (e.g., `// gets the user id` above `getUserId()`).
- **Quality**: Run `evaluate_comment_quality` to assess the overall usefulness of the documentation.
</step>

<step id="4" name="Synthesis & Formatting">
- Synthesize all findings from the offloaded JSON files into a structured markdown report.
- Point the user directly to risky code changes, predicted merge conflicts, or useless LLM-generated comments.
</step>
</workflow>

<format_requirements>
1. **Structured Data**: Leverage the rich structures returned by the tools to confidently generate tables, summaries, and charts without brittle string parsing. Do not dump raw JSON.
2. **Alerts**: Use Github-flavored markdown alerts (`> [!WARNING]`, `> [!IMPORTANT]`) to highlight predicted merge conflicts or highly risky PR diffs.
</format_requirements>
''';
}
