name: Agnostic Code Metrics
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rw-core/agnostic-code-metrics@v1