name: coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1

      - name: Clean Dart
        run: dart pub cache clean

      - name: Install dependencies
        run: dart pub get
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed --line-length=80 .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: |
          dart test --coverage=coverage
          dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: coverage/lcov.info
          token: "${{ secrets.CODECOV_TOKEN }}"
